FROM bitnami/kafka:3.4.1

COPY ./connectors/debezium-connector-postgres /opt/connectors/debezium-connector-postgres

COPY ./config/debezium-connect-distributed.properties /opt/bitnami/kafka/config/connect-distributed.properties

CMD ["/opt/bitnami/kafka/bin/connect-distributed.sh", "/opt/bitnami/kafka/config/connect-distributed.properties"]
